# Generated by Django 5.0.6 on 2024-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_options_product_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='USA', max_length=40),
        ),
        migrations.AddField(
            model_name='customer',
            name='postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address1',
            field=models.CharField(default='Unknown', max_length=80),
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address2',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='town_or_city',
            field=models.CharField(default='Unknown', max_length=40),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
