# Generated by Django 5.0.6 on 2024-08-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_customer_address_customer_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
    ]
